#include "ip.h"
#include "icmp.h"
#include "arpcache.h"
#include "rtable.h"
#include "arp.h"
#include "log.h"
#include <stdlib.h>
#include <assert.h>
#include <arpa/inet.h> 

// initialize ip header 
void ip_init_hdr(struct iphdr *ip, u32 saddr, u32 daddr, u16 len, u8 proto)
{
	ip->version = 4;
	ip->ihl = 5;
	ip->tos = 0;
	ip->tot_len = htons(len);
	ip->id = rand();
	ip->frag_off = htons(IP_DF);
	ip->ttl = DEFAULT_TTL;
	ip->protocol = proto;
	ip->saddr = htonl(saddr);
	ip->daddr = htonl(daddr);
	ip->checksum = ip_checksum(ip);
}

// lookup in the routing table, to find the entry with the same and longest prefix
// The input address is in host byte order.
// Tips:
// rtable is a global variable defined in rtable.c
rt_entry_t *longest_prefix_match(u32 dst)
{
	//assert(0 && "TODO: function longest_prefix_match not implemented!");
	//return NULL;
    rt_entry_t *best_match = NULL;
    u32 longest_prefix = 0;

    // 遍历全局路由表 rtable
    rt_entry_t *entry = NULL;
    list_for_each_entry(entry, &rtable, list) {
        // 检查当前路由表条目是否匹配目标地址
        if ((dst & entry->mask) == (entry->dest & entry->mask)) {
            // 如果匹配，检查前缀长度是否更长
            if (entry->mask > longest_prefix) {
                longest_prefix = entry->mask;
                best_match = entry;
            }
            
        }
    }

    return best_match; // 返回匹配的路由表条目（如果没有匹配则返回NULL）
//这里没有加上rt_lock的锁，待后续研究
//检查完毕，修改了遍历逻辑
}

// different from function ip_forward_packet, ip_send_packet sends packet generated by router itself
// This function is used to send icmp packets.
// You can complete this function after completing icmp_send_packet, or directly integrate the function into icmp_send_packet.
// The interface to sendd the packet is specified by longest_prefix_match.
void ip_send_packet(char *packet, int len)
{
	//assert(0 && "TODO: function ip_send_packet not implemented!");
    // 获取IP头部
    log(DEBUG, "ip_send_packet");
    struct iphdr *ip = packet_to_ip_hdr(packet);

    // 查找路由表，确定下一跳
    rt_entry_t *entry = longest_prefix_match(ntohl(ip->daddr));


  
    if (!entry) {
        // 如果无法找到路由表条目，记录错误并丢弃数据包
        log(ERROR, "No route to host for IP packet.");
        free(packet);
        return;
    }

    // 确定下一跳地址
    u32 next_hop = (entry->gw == 0) ? ntohl(ip->daddr) : entry->gw;

    // 通过接口发送数据包
    iface_send_packet_by_arp(entry->iface, next_hop, packet, len);
//检查完毕，基本符合要求
}
