#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>     
#include <sys/wait.h>   
#include <sys/time.h>  
#include <fcntl.h>     
// Feel free to change the data structures generated by AI.

#define MAX_SYSCALLS 1024
#define TOP_N 5
#define TimeToPrint 100


typedef struct {
    char name[64];
    double time;
} syscall_stat;

typedef struct {
    syscall_stat stats[MAX_SYSCALLS];
    int count;
    double total_time;
} syscall_stats;

int parse_strace_line(char *line, char *syscall_name, double *time) {
    if (strstr(line, "+++ exited with") || strstr(line, "--- SIG")) {
        return -1;
    }//ignore the line with exit or signal
        
    char *name = strchr(line, '(');
    if (name == NULL) {
        return -1; // Invalid line format
    }
    size_t len = name - line;
    if(len >= 64) {
        return -1; // Syscall name too long
    }
    strncpy(syscall_name, line, len);
    syscall_name[len] = '\0';//get the syscall name

    char *left = strchr(name, '<');
    char *right = strchr(name, '>');
    if(left == NULL || right == NULL || left >= right) {
        return -1; // Invalid line format
    }
    char time_str[right - left + 1];
    strncpy(time_str, left + 1, right - left - 1);
    time_str[right - left - 1] = '\0';
    *time = atof(time_str);//get the time
    return 0;
}

void add_syscall(syscall_stats *stats, const char *name, double time) {
    for(int i = 0; i < stats->count; i++){
        if(strcmp(stats->stats[i].name, name) == 0){
            stats->stats[i].time += time;
            stats->total_time += time;
            return;
        }
    }//check if the syscall already exists
    
    if(stats->count < MAX_SYSCALLS){
        int index = stats->count;
        stats->count++;
        strncpy(stats->stats[index].name, name,63);
        stats->stats[index].name[63] = '\0'; // Ensure null-termination
        stats->stats[index].time = time;
        stats->total_time += time;
    }
    else{
        int min_index = 0;//exchange the min time process
        for(int i = 1; i < MAX_SYSCALLS; i++){
            if(stats->stats[i].time < stats->stats[min_index].time){
                min_index = i;
            }
        }
        if(stats->stats[min_index].time < time){
            stats->total_time -= stats->stats[min_index].time;
            strcpy(stats->stats[min_index].name, name);
            stats->stats[min_index].time = time;
            stats->total_time += time;
        }
    }
}

void print_top_syscalls(syscall_stats *stats, int n) {
    //choose the top n syscalls
    if(n > TOP_N){
        n = TOP_N;
    }

    for(int i = 0; i < n; i++){
        int max_idx = i;
        for(int j = i + 1; j < stats->count; j++){
            if(stats->stats[max_idx].time < stats->stats[j].time){
                max_idx = j;//find the max time syscall
            }
        }
        if(max_idx != i){
            syscall_stat temp = stats->stats[i];
            stats->stats[i] = stats->stats[max_idx];
            stats->stats[max_idx] = temp;
        }
    }

    for(int i = 0; i < n; i++) {
        printf("%s (%d%%)\n", stats->stats[i].name, (int)(stats->stats[i].time / stats->total_time * 100));
    }
    fflush(stdout);
    for (int i = 0; i < 80; i++) {
        putchar('\0');//解决2
    }
}


char* find_executable(const char* name) {

    char* env = getenv("PATH");
    if (!env) {
        env = "/usr/bin:/bin";
    }
    
    char* cpy = strdup(env);
    
    char* result = NULL;
    char* path_token = strtok(cpy, ":");
    
    while (path_token != NULL) {
        char full_path[4096];
        snprintf(full_path, 4096, "%s/%s", path_token, name);
        
        if (access(full_path, X_OK) == 0) {
            result = strdup(full_path);
            break;
        }
        
        path_token = strtok(NULL, ":");
    }
    
    free(cpy);
    return result;
}


int main(int argc, char *argv[]) {

    if (argc < 2) {
        printf( "Usage: %s <command> [args...]\n", argv[0]);
        return 0;
    }
    int pipe_fd[2];// Create a pipe

    if (pipe(pipe_fd) == -1) {
        printf("Error creating pipe\n");
        return 0;
    }
    pid_t pid = fork();

    if(pid == 0){
        close(pipe_fd[0]); // Close the read end of the pipe in the child process
        dup2(pipe_fd[1], STDOUT_FILENO); // Redirect stdout to the write end of the pipe
        // 子进程部分添加
        dup2(pipe_fd[1], STDERR_FILENO);  // 新增这行
        close(pipe_fd[1]);
        
        char *new_argv[argc+2]; 
        new_argv[0] = "strace";
        new_argv[1] = "-T";

        if(argv[1][0] == '/'){
            new_argv[2] = argv[1]; // Use the full path directly
        }
        else{
            char *cmd_path = find_executable(argv[1]);
            new_argv[2] = cmd_path; // Use the path found in PATH
        }
        char *cmd_path = find_executable(argv[1]);
        new_argv[2] = cmd_path; // Use the path found in PATH


        for(int i = 2; i < argc; i++){
            new_argv[i+1] = argv[i];
        }
        new_argv[argc+1] = NULL; //准备新的argv
        execve("/usr/bin/strace", new_argv, __environ); // Execute strace with the command and arguments

    }
        


    else{
        close(pipe_fd[1]); // Close the write end of the pipe in the parent process
        
        syscall_stats stats;
        stats.count = 0;
        stats.total_time = 0;//initialize the stats
        struct timeval last;
        gettimeofday(&last, NULL);
       
        
        char line_buffer[4096] = {0};
        size_t line_length = 0;
        
        while(1){
            
            if (waitpid(pid, NULL, WNOHANG) > 0) {
                break; // Child process has finished
            }

            fd_set read_fds;
            FD_ZERO(&read_fds);
            FD_SET(pipe_fd[0], &read_fds);
        

            struct timeval timeout = {0, 100000}; // 100ms
            int ret = select(pipe_fd[0]+1, &read_fds, NULL, NULL, &timeout);//防止阻塞，很重要，不然会出错

            if (ret > 0 && FD_ISSET(pipe_fd[0], &read_fds)) {
                //printf("1-----------------------------------------------\n");
                ssize_t bytes_read = read(pipe_fd[0], line_buffer + line_length, sizeof(line_buffer) - line_length - 1);
                if (bytes_read <= 0) {
                    break; // End of input or error
                }
                //printf("2-----------------------------------------------\n");
                line_length += bytes_read;
                line_buffer[line_length] = '\0'; // Null-terminate the string
                
                char *start = line_buffer;
                char *end;
                //printf("3-----------------------------------------------\n");
                while((end = strchr(start, '\n')) != NULL){
                    *end = '\0';
                    if (line_length > 0) {
                        char syscall_name[64];
                        double time;
                        if(parse_strace_line(start, syscall_name, &time) == 0){
                            add_syscall(&stats, syscall_name, time);
                        }
                    }
                    start = end + 1;
                    
                }
                if(start != line_buffer){ 
                    line_length -= (start - line_buffer);
                    memmove(line_buffer, start, line_length);
                    line_buffer[line_length] = '\0'; // Null-terminate the string
                }
                //printf("4-----------------------------------------------\n");

            }
            
            

            struct timeval now;//距离上次输出还有多久
            gettimeofday(&now, NULL);

            //printf("----------now: %ld.%06ld\n", now.tv_sec, now.tv_usec);
            //printf("----------last: %ld.%06ld\n", last.tv_sec, last.tv_usec);
            long elapsed_ms = (now.tv_sec - last.tv_sec) * 1000 + (now.tv_usec - last.tv_usec) / 1000;
            //printf("elapsed_ms---------------------: %ld\n", elapsed_ms);
            if(elapsed_ms > TimeToPrint){
               
                if(stats.count < TOP_N){
                    //printf("--------Not enough syscalls to print\n");
                    //printf("Total syscalls: %d\n", stats.count);    
                    print_top_syscalls(&stats, stats.count);
                }
                else{
                    //printf("---------Enough syscalls to print\n");
                    print_top_syscalls(&stats, TOP_N);
                }   
                fflush(stdout);
                gettimeofday(&last, NULL);
            }
        }

        print_top_syscalls(&stats, TOP_N);
        close(pipe_fd[0]); // Close the read end of the pipe in the parent process
        waitpid(pid, NULL, 0); // Wait for the child process to finish
    }

    
    return 0;
}
